# Basis-Image mit Node
FROM node:22-alpine AS backend

# Arbeitsverzeichnis erstellen, in dem die folgenden Befehle (COPY, RUN) ausgeführt werden.
WORKDIR /usr/src/app

# Abhängigkeiten kopieren und installieren
COPY package*.json .
RUN npm install

# Anwendungscode kopieren (z.B. einfach alle js-Dateien)
COPY . /usr/src/app
COPY ./routes /usr/src/app/routes

# Port freigeben (Port, der in Ihrem Backend konfiguriert ist)
EXPOSE 10062

# Startbefehl 
CMD ["node", "app.js"]
